export const GET_CURRENCIES_REQUESTED = 'GET_CURRENCIES_REQUESTED'
export const GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS'
export const GET_CURRENCIES_FAILED = 'GET_CURRENCIES_FAILED'

export const CONVERT_CURRENCY_REQUESTED = 'CONVERT_CURRENCY_REQUESTED'
export const CONVERT_CURRENCY_SUCCESS = 'CONVERT_CURRENCY_SUCCESS'
export const CONVERT_CURRENCY_FAILED = 'CONVERT_CURRENCY_FAILED'
